In [25]:
import numpy as np
import pandas as pd

In [26]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [28]:
data = load_diabetes()
x = data.data
y = data.target


In [29]:
# Convert target to binary using median
y_binary = (y > np.median(y)).astype(int)


In [34]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y_binary,
    test_size=0.2,
    random_state=42,
    stratify=y_binary
    )

In [31]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)


In [37]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train_scaled, y_train)
knn_pred = knn.predict(x_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test, knn_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, knn_pred))
print("Classification Report:\n",classification_report(y_test, knn_pred))


KNN Accuracy: 0.5168539325842697
Confusion Matrix:
 [[24 21]
 [22 22]]
Classification Report:
               precision    recall  f1-score   support

           0       0.52      0.53      0.53        45
           1       0.51      0.50      0.51        44

    accuracy                           0.52        89
   macro avg       0.52      0.52      0.52        89
weighted avg       0.52      0.52      0.52        89



In [38]:
lr_liblinear = LogisticRegression(solver='liblinear')

lr_liblinear.fit(x_train_scaled, y_train)
liblinear_pred = lr_liblinear.predict(x_test_scaled)

print("Logistic Regression (liblinear) Accuracy:",
      accuracy_score(y_test, liblinear_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, liblinear_pred))
print("Classification Report:\n",classification_report(y_test, liblinear_pred))


Logistic Regression (liblinear) Accuracy: 0.4943820224719101
Confusion Matrix:
 [[22 23]
 [22 22]]
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.49      0.49        45
           1       0.49      0.50      0.49        44

    accuracy                           0.49        89
   macro avg       0.49      0.49      0.49        89
weighted avg       0.49      0.49      0.49        89



In [41]:
lr_lbfgs = LogisticRegression(
    solver="lbfgs",
    max_iter=1000
)
lr_lbfgs.fit(x_train_scaled, y_train)

lbfgs_pred = lr_lbfgs.predict(x_test_scaled)
print("Logistic Regression (lbfgs) Accuracy:",
      accuracy_score(y_test, lbfgs_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, lbfgs_pred))
print("Classification Report:\n",classification_report(y_test, lbfgs_pred))

Logistic Regression (lbfgs) Accuracy: 0.4943820224719101
Confusion Matrix:
 [[22 23]
 [22 22]]
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.49      0.49        45
           1       0.49      0.50      0.49        44

    accuracy                           0.49        89
   macro avg       0.49      0.49      0.49        89
weighted avg       0.49      0.49      0.49        89

